// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACYKKddYgjvab5SG0Q1VA1vBHQ-civmbk',
    appId: '1:1044264109115:web:3fc3ab9d616461f21d881e',
    messagingSenderId: '1044264109115',
    projectId: 'fixi-pro',
    authDomain: 'fixi-pro.firebaseapp.com',
    storageBucket: 'fixi-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApJosoAndy0w0SygY1UE_Eq0NKeFUenUY',
    appId: '1:1044264109115:android:5e31506e6c85f4851d881e',
    messagingSenderId: '1044264109115',
    projectId: 'fixi-pro',
    storageBucket: 'fixi-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZAj0reccWbD2zUCbjl9d6lvMA37sZhZU',
    appId: '1:1044264109115:ios:b1f7c981d1d49fa41d881e',
    messagingSenderId: '1044264109115',
    projectId: 'fixi-pro',
    storageBucket: 'fixi-pro.firebasestorage.app',
    iosBundleId: 'com.example.fixitPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZAj0reccWbD2zUCbjl9d6lvMA37sZhZU',
    appId: '1:1044264109115:ios:b1f7c981d1d49fa41d881e',
    messagingSenderId: '1044264109115',
    projectId: 'fixi-pro',
    storageBucket: 'fixi-pro.firebasestorage.app',
    iosBundleId: 'com.example.fixitPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACYKKddYgjvab5SG0Q1VA1vBHQ-civmbk',
    appId: '1:1044264109115:web:1388d62d258880361d881e',
    messagingSenderId: '1044264109115',
    projectId: 'fixi-pro',
    authDomain: 'fixi-pro.firebaseapp.com',
    storageBucket: 'fixi-pro.firebasestorage.app',
  );

}